# Generated by Django 5.0.3 on 2024-06-05 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('fat', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('serving_size', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='breakfast', max_length=10)),
                ('servings', models.FloatField()),
                ('date', models.DateField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition_tracker_app.food')),
                ('username', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
