# Generated by Django 5.0.6 on 2024-07-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_tracker_app', '0002_remove_mealentry_username_mealentry_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.IntegerField(),
        ),
    ]
