# Generated by Django 5.0.2 on 2025-04-07 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_tracker_app', '0003_alter_food_carbs_alter_food_fat_alter_food_protein'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Food', 'verbose_name_plural': 'Foods'},
        ),
        migrations.AlterModelOptions(
            name='mealentry',
            options={'verbose_name': 'MealEntry', 'verbose_name_plural': 'MealEntries'},
        ),
    ]
