# Generated by Django 5.0.2 on 2024-03-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0002_workout_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sets',
            name='set_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
