# Generated by Django 5.0.2 on 2024-03-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0004_alter_workout_workout_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='user_id',
            new_name='username',
        ),
    ]
