# Generated by Django 5.0.2 on 2024-03-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker_app', '0003_alter_exercise_exercise_id_alter_sets_set_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
