# Generated by Django 5.0.2 on 2024-03-20 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker_app', '0008_delete_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='workout_id',
            new_name='workout',
        ),
        migrations.RenameField(
            model_name='sets',
            old_name='exercise_id',
            new_name='exercise',
        ),
    ]
