# Generated by Django 5.0.3 on 2024-03-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker_app', '0009_rename_workout_id_exercise_workout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
