# Generated by Django 5.0.6 on 2024-07-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker_app', '0012_alter_exercise_workout_alter_sets_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='calories_burned',
            field=models.IntegerField(default=0),
        ),
    ]
