# Generated by Django 5.0.6 on 2024-07-02 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker_app', '0013_workout_calories_burned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='username',
            new_name='user',
        ),
    ]
