# Generated by Django 5.0.6 on 2025-04-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker_app', '0015_workout_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
