# Generated by Django 5.0.6 on 2025-04-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker_app', '0019_workout_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='duration',
        ),
        migrations.AddField(
            model_name='workout',
            name='active_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='last_active_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
