# Generated by Django 5.0.3 on 2024-06-23 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='username',
            new_name='user',
        ),
    ]
