# Generated by Django 5.0.3 on 2024-06-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_rename_username_info_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='calorie_intake',
            field=models.IntegerField(blank=True),
        ),
    ]
