# Generated by Django 5.0.6 on 2024-06-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_info_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='activity_level',
            field=models.CharField(choices=[('1', 'No Activity'), ('2', 'Active 1-2 times a week'), ('3', 'Active 3-5 times a week'), ('4', 'Active 6-7 times a week'), ('5', 'Athlete')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='info',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=1),
        ),
    ]
