# Generated by Django 5.0.6 on 2024-06-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_info_activity_level_alter_info_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='weight_goal',
            field=models.CharField(choices=[('L2', 'Lose 2 pounds per week'), ('L1', 'Lose 1 pound per week'), ('M', 'Maintain weight'), ('G1', 'Gain 1 pound per week'), ('G2', 'Gain 2 pounds per week')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='info',
            name='activity_level',
            field=models.CharField(choices=[('1', 'Little to no activity'), ('2', 'Exercise 1-3 days a week'), ('3', 'Active 3-5 days a week'), ('4', 'Exercise 6-7 days a week'), ('5', 'Intense exercise 6-7 days a week')], default='Lightly Active', max_length=1),
        ),
    ]
