# Generated by Django 5.0.2 on 2024-06-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0007_info_weight_goal_alter_info_activity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='age',
            field=models.IntegerField(default=40),
        ),
    ]
