# Generated by Django 5.0.6 on 2024-07-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0009_info_weight_goal_pounds_alter_info_activity_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='weight_goal',
            field=models.CharField(choices=[('lose', 'Lose Weight'), ('maintain', 'Maintain Weight'), ('gain', 'Gain Weight')], default='maintain', max_length=10),
        ),
        migrations.AlterField(
            model_name='info',
            name='weight_goal_pounds',
            field=models.DecimalField(choices=[(0, '0 pounds per week (maintain)')], decimal_places=1, default=0, max_digits=4),
        ),
    ]
