# Generated by Django 5.0.6 on 2024-07-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0012_weightgoalpounds_alter_info_weight_goal_pounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='weight_goal_pounds',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.DeleteModel(
            name='WeightGoalPounds',
        ),
    ]
