# Generated by Django 5.0.6 on 2024-07-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0015_alter_info_weight_goal_pounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='has_completed',
            field=models.BooleanField(default=False),
        ),
    ]
