# Generated by Django 5.0.2 on 2025-04-07 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0016_info_has_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Info', 'verbose_name_plural': 'Info'},
        ),
    ]
