# Generated by Django 5.0.2 on 2025-04-07 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0017_alter_info_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='height',
            new_name='height_inches',
        ),
    ]
