# Generated by Django 5.0.2 on 2024-03-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0005_rename_user_id_workout_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
