# Generated by Django 5.0.2 on 2024-03-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0007_alter_sets_set_id_alter_workout_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
