# Generated by Django 5.0.3 on 2024-03-26 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0010_exercise_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='volume',
        ),
    ]
